### ISSUE TITLE
Unable to see examples in the 'Examples' Tab on selecting a specific device

### ISSUE THREAD

**Issue by avi-77** [ARM-software/cmsis-pack-eclipse#104]
Hi @edriouk,

In the CMSIS pack manager plugin version 2.8.0, I'm unable to see the examples in the 'Examples' Tab on selecting a specific device. 
![Examples_Tab_Specific_Device](https://user-images.githubusercontent.com/79654418/196242364-bbc07933-1c38-4df8-8bc6-da18e102b5f3.PNG)
Although, I'm able to see the examples in the 'Examples' Tab on selecting All Devices as shown in the figure below.
![Examples_Tab_All_Devices](https://user-images.githubusercontent.com/79654418/196242444-bab82716-e281-451a-b983-eaba99f2acd6.PNG)

Please note, I have installed the com.arm.cmsis.pack.refclient plugin. It was working fine in version 2.7.0. Could you please look into this issue for the next release?

**Comment by edriouk** [comment]
Hi, 
that is a problem of comparing board IDs 
Board description:
`<board name="RSL10 Evaluation Board" revision="1.0" vendor="ONSemiconductor">`
Board ID: 
`board description is ONSemiconductor::RSL10 Evaluation Board (1.0)`
example board description:
`<board name="RSL10 Evaluation Board" vendor="ONSemiconductor"/>`
example board ID :
`ONSemiconductor::RSL10 Evaluation Board`

Boards of different revisions are treated as incompatible => check fails for a selected board/device on that board
This rule has been enforced in 2.8.0 because of adding Board Support functionality.
I agree that it can be made less restrictive to display available examples. 
Will be planned for the next release
Evgueni

**Comment by andrewmclachlanadi** [comment]
Seeing this issue too. It's a noticable difference from previous releases and therefore looks like a severe bug.

**Comment by edriouk** [comment]
Fixed in 2.9.0
