### ISSUE TITLE
RTE Config variant not set to one I selected during project creation 

### ISSUE THREAD

**Issue by JohnKBartholomew** [ARM-software/cmsis-pack-eclipse#33]
When I create a new project and select a device in the new project wizard - I expect that device variant to show up as the "variant" field value in the RTE Config file that opens up when the project creation completes. 

In my case I have created several variants of a device, and I select variant 3 from the displayed list on the "Select Device" page of the new project wizard. In the RTE Config pane, however, the "variant" field for my Device/Startup and Device/Header lines are set to device variant 1 as a default. 

To get my design to build as expected, I have to select the variant field on both these lines and set it back to variant 3. (As the names are close, I hadn't noticed this error and it took me a whiel to track down!)  I had expected that selecting variant 3 during project creation would automatically set these fields in the RTE Config window, but it did not.

My Packs' PDSC file  entries for Device and Startup include the correct Cvariant attribute value, so there's not a problem there. Could you please check the CMSIS-Pack Mgmt plugin code to see if the value being added to the RTE Config window is selecting the wrong variant somehow?

**Comment by edriouk** [comment]
Hi John,
Cvariant and Dvariant attributes are completely independent from each other. They represent different semantics.

Dvariant is a vendor-specific device classification attribute. CMSIS pack management uses it to identify unique device name if Dvariant attribute is present in device description, otherwise Dname attribute is used. 

Cvariant is used for software component classification to implement "one of" behavior. In some cases can refer to a board or a device, but mostly to component functionality, e.g. Long File Names vs Short File Names for  "File Sytem.CORE" component. It is possible to define a default Cvariant for a component.

Please note that every device variant can use its own define and/or header in <compile> element.
It is advised to use single Device.Startup component (without Cvariant) for the entire device family  and use device defines to configure startup code for a particular device variant.
