### ISSUE TITLE
CpPackInstaller unconditionally replaces url with http://www.keil.com/pack

### ISSUE THREAD

**Issue by jesperes** [ARM-software/cmsis-pack-eclipse#51]
In `CpPackInstaller#aggregateCmsis()`, the "url" part is unconditionally replaced with `CmsisConstants.REPO_KEIL_PACK_SERVER`:

			final String pdscUrl = CmsisConstants.REPO_KEIL_PACK_SERVER;
                        ...
			downloadPdscFile(pdscUrl, pdscName, destFileName);

Is this a bug, or is there a reason for doing this? It effectivly means that we need to reimplement this code in our own pack installer. This was changed in d77f54c48ee1096caceb9741855427e82df81c75, but there is no comment on this particular modification to shed any light on why it was done.

**Comment by edriouk** [comment]
That is a bug since it is ARM-speific soultion. 

The previous code `pdscUrl = Utils.addTrailingSlash(pdsc[0]); ` should be used, it works always. 
However if you cache external pdsc files on your server, you migh prefer to use similar slution as we do.
Though the right code would be not to hard-code the URL, but request it via ` ICpRepositry.getUrl() `,
ICpRepository reperesent an pack index location entry in CMSIS pack preferences.  The problem here is that we cannot code it directly as we do not know if a particular index location caches the pdsc files.

Note that pack download should always follow URL described in pdsc itself.
