### ISSUE TITLE
Does this support command line to import packs ?

### ISSUE THREAD

**Issue by Hoohaha** [ARM-software/cmsis-pack-eclipse#56]
Hi sirs，

I work with ds-mdk & iar.
There are bulit-in cmsis-pack-eclipse tool.

How could i import packs by command line?
And where the location of packs is installed on linux?

**Comment by edriouk** [comment]
Hi,

There is no command-line pack management tool for Linux. On Windows you can use PackUnzip.exe and PackInstaller.exe from MDK ARM (http://www2.keil.com/mdk5/), those executables do dot require license.

You define the pack location via Eclipse preferences:  Window->Preferences->CMSIS Packs

What do you mean under pack import : 
 - download and install an available pack ?
 - unpack locally available pack?

**Comment by jkrech** [comment]
The eclipse plug-ins only support the pack installation using the GUI.
Since the *.pack files are regular zip archives you can use unzip to extract the archive into a folder.
In order to avoid conflicts with the pack manager GUI plug-in you should follow the folder naming convention. A pack gets extracted into the folder named <vendor>/<pack name>/<pack version> where version is limited to <major>.<minor>.<patch>[-...] (+... is ignored).

**Comment by Hoohaha** [comment]
In my situation, a lot of local packs need to be installed to IDE,  so we want to using to script to achieve athe automated installation. As far as i know ARM MDK provide a friednly tool named "PackUnzip.exe", but for cmsis-pack-eclipse we have no idea. @jkrech i think you advice is a good solution.

**Comment by marguzmar** [comment]
Question was answered.
