### ISSUE TITLE
the command line options in armasm 6.10.1 are not compatible with the settings in this plugin

### ISSUE THREAD

**Issue by paperchalice** [ARM-software/cmsis-pack-eclipse#67]
Maybe arm update the assembler and some options are deprecated or old, for example: "Warning: A3910W: Old syntax, please use '--cpu' "
therefore I must use the Miscellaneous to solve it, will you have plan to update this plugin?
Thanks.

**Comment by edriouk** [comment]
Hi,
In what environment do you use the Arm Compiler toolchain? 
Could you please attach a screenshot of Project C/C++ Build Settings.

**Comment by paperchalice** [comment]
<img width="781" alt="asm_settings" src="https://user-images.githubusercontent.com/29250197/43430861-afbd5076-949d-11e8-9a6e-2c39092e6c3b.PNG">
and in "Tool Chan Editor", I can't replace the "Arm Assembler 6.10" with "Arm Assembler 5.6.6", in this settings page, the options are OK.
<img width="781" alt="replace" src="https://user-images.githubusercontent.com/29250197/43430949-20bd931c-949e-11e8-838f-eda19d2918a2.PNG">


Version: Photon Release (4.8.0)
Build id: 20180619-1200

**Comment by edriouk** [comment]
HI, 

As I can see from your screenshots the toolchain you use contains two assemblers 5.6.6 and 6.10.
Have you configured them manually? 
Do you set file-specific compiler settings or only project-wide? 
Which from assemlers is actually called? 

This issue is not directly related to CMSIS Eclipse plug-in since it does not construct any command line option. It just passes required information to Eclipse toolchain for Arm Compiler 6, that plug-in constructs the command line.   
The Eclipse toolchain for Arm Compiler 6 is a separate plug-in that is normally delivered with Arm DS-5 or Arm DS-MDK products. You should probably contact Arm Support for this issue.

**Comment by paperchalice** [comment]
Hello, 
Yes,  in the past I can use armasm to assemble the code written in arm syntax, and after I configured tools manually, the assembler 6.10 appears again, all the settings are project-wide
